workflows:
  benchmark:
    environment:
      xcode: 13.2.1
    scripts:
      - name: Run benchmark
        script: |
          set -e # exit on first failed command
          sudo chmod +x benchmark.sh
          ./benchmark.sh
    artifacts:
      - build/ios/*
